bbr:
  name: body-based-router
  replicas: 1
  image:
    registry: us-central1-docker.pkg.dev/k8s-staging-images
    repository: gateway-api-inference-extension/bbr
    tag: main
    pullPolicy: Always
  port: 9004
  healthCheckPort: 9005
  multiNamespace: false

  flags:
    # Log verbosity
    v: 3

  # Plugin configuration (transitional - currently runs no-op default plugin)
  plugins:
    - type: default-bbr
      name: default-bbr
      json: {"v":0, "no-op":true}

provider:
  name: none

inferenceGateway:
  name: inference-gateway
